name: Redis CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Helm 3
      uses: azure/setup-helm@v1
      with:
       version: 'v3.0.0-beta.5'
      id: install
    - name: Deploy to k8s
      run: | 
        echo "$SECRET_CONFIG" > /home/runner/config
        /opt/hostedtoolcache/helm/3.0.0-beta.5/x64/linux-amd64/helm upgrade --atomic --set password=${MY_PASSWORD} -f values.yaml redis-release stable/redis
      env:
        KUBECONFIG: /home/runner/config
        SECRET_CONFIG: ${{ secrets.KUBE_CONFIG }}
        MY_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
